### ISSUE TITLE
Completion mode

### ISSUE THREAD

**Issue by lu5her-s** [kiddos/gemini.nvim#4]
How to insert completion,
and after update pop-up is not show

**Comment by kiddos** [comment]
yeah, I made some changes. I try to copy how copilot did its completion.

It looks like this.

https://github.com/kiddos/gemini.nvim/assets/9444583/e042d1ac-c79d-48b1-b676-62ac738a7038

default press `<S-Tab>` to insert the text

And for the original function hints, I made it so that it trys to insert comments above.

https://github.com/kiddos/gemini.nvim/assets/9444583/191d0da0-ad2f-49ae-a2ac-5530a7bff558

**Comment by kiddos** [comment]
could you provide a little more information?
or maybe logs?

**Comment by lu5her-s** [comment]
Ok found it,problem from duplicate with codeium.
Thank.

**Comment by lu5her-s** [comment]
@kiddos I change insert key from <S-tab> to <C-O> it  worked
